version: '3'
services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data
  mysql:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    image: mysql:5
    restart: always
    environment:
      MYSQL_DATABASE: superset
      MYSQL_PASSWORD: superset
      MYSQL_ROOT_PASSWORD: superset
      MYSQL_USER: superset
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
  postgres_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres_db:/var/lib/postgresql/data
  superset:
    image: amancevice/superset
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
    ports:
      - "8088:8088"
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py
networks:
  default:
    name: airflow-network      
volumes:
  mysql:
  redis:
  postgres_db: