- columns:
  - column_name: birth_date
    is_dttm: true
    type: DATE
  - column_name: hire_date
    is_dttm: true
    type: DATE
  - column_name: postal_code
    type: VARCHAR(10)
  - column_name: first_name
    type: VARCHAR(10)
  - column_name: last_name
    type: VARCHAR(20)
  - column_name: title
    type: VARCHAR(30)
  - column_name: address
    type: VARCHAR(60)
  - column_name: city
    type: VARCHAR(15)
  - column_name: country
    type: VARCHAR(15)
  - column_name: region
    type: VARCHAR(15)
  - column_name: home_phone
    type: VARCHAR(24)
  - column_name: photo_path
    type: VARCHAR(255)
  - column_name: title_of_courtesy
    type: VARCHAR(25)
  - column_name: extension
    type: VARCHAR(4)
  - column_name: photo
    type: BYTEA
  - column_name: employee_id
    type: SMALLINT
  - column_name: reports_to
    type: SMALLINT
  - column_name: notes
    type: TEXT
  main_dttm_col: birth_date
  metrics:
  - expression: COUNT(*)
    metric_name: count
    metric_type: count
    verbose_name: COUNT(*)
  schema: public
  table_name: employees
