- columns:
  - column_name: customer_desc
    type: TEXT
  - column_name: customer_type_id
    type: UNKNOWN
  metrics:
  - expression: COUNT(*)
    metric_name: count
    metric_type: count
    verbose_name: COUNT(*)
  schema: public
  table_name: customer_demographics
