- columns:
  - column_name: territory_id
    type: VARCHAR(20)
  - column_name: employee_id
    type: SMALLINT
  metrics:
  - expression: COUNT(*)
    metric_name: count
    metric_type: count
    verbose_name: COUNT(*)
  schema: public
  table_name: employee_territories
