- columns:
  - column_name: quantity_per_unit
    type: VARCHAR(20)
  - column_name: product_name
    type: VARCHAR(40)
  - column_name: unit_price
    type: REAL
  - column_name: units_in_stock
    type: SMALLINT
  - column_name: units_on_order
    type: SMALLINT
  - column_name: category_id
    type: SMALLINT
  - column_name: product_id
    type: SMALLINT
  - column_name: reorder_level
    type: SMALLINT
  - column_name: supplier_id
    type: SMALLINT
  - column_name: discontinued
    type: INTEGER
  metrics:
  - expression: COUNT(*)
    metric_name: count
    metric_type: count
    verbose_name: COUNT(*)
  schema: public
  table_name: products
