- columns:
  - column_name: unit_price
    type: REAL
  - column_name: discount
    type: REAL
  - column_name: product_id
    type: SMALLINT
  - column_name: order_id
    type: SMALLINT
  - column_name: quantity
    type: SMALLINT
  metrics:
  - expression: COUNT(*)
    metric_name: count
    metric_type: count
    verbose_name: COUNT(*)
  schema: public
  table_name: order_details
